spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/licoy/spring-cloud-study-config.git
          default-label: master
          search-paths: respo
      discovery:
        enabled: true
        service-id: ${spring.application.name}
#          公开仓库无需账号密码
#          username:
#          password:
  rabbitmq:
      host: 118.24.24.243
      port: 5672
      username: springcloud
      password: 123456
server:
  port: 8000
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
management:
  security:
    enabled: false