spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/Licoy/spring-cloud-config-repo
          username:
          password:
          basedir: F:\dev\java\springcloud-learning\basedir
  rabbitmq:
    host:
    port: 5672
    username: admin
    password: 123456
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
management:
  endpoints:
    web:
      exposure:
        include: "*"
server:
  port: 8080