spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/licoy/spring-cloud-study-config.git
          default-label: master
          search-paths: respo
#          公开仓库无需账号密码
#          username:
#          password:
server:
  port: 8000
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/